### ISSUE TITLE
Size of the 3D object

### ISSUE THREAD

**Issue by Kartheek410** [MarcDAFrame/img2stl#1]
It was perfectly alright and working. I wanted to have a file where the 3D object sizes to be manipulated as desired. For example, if I give an image which is of 256x256 png, the 3D object also visible as 256x256x256 in pixel size. When I decrease the pixels in a 2D image to 50x50, the Z-axis of the 3D object couldn't be changed as per the x- & y-axes. It remains the same as 256 pixels.

Is there a way to change the pixel size as we desired? Where could it be changed or modified?

Thank you for your time.
Please let me know if I didn't explain it clearly.
-K

**Comment by MarcDAFrame** [comment]
My goodness, Haven't looked at this code in a long time!

I suppose you would want to change these lines 28-31
```
                    [x, y, 255-pixel],
                    [x+1, y, 255-pixel],
                    [x+1, y+1, 255-pixel], 
                    [x, y+1, 255-pixel],
```

where the 255 could be whatever height you want it to be

**Comment by Kartheek410** [comment]
@MarcDAFrame 
_*Please copy and paste the link in the new tab if the direct link doesn't work.*_
Hi, thank you for the reply though (it was a hope).
I tried, but changing that value messes up with the base of the output. I mean, when I change the values the base gets thicker and the important pixels are getting covered in that thick baseline.
You could see what's the problem here in the images that I attached [https://imgur.com/Y2CItp5](url) .
If I change the 255 values as you suggested this was the problem [https://imgur.com/ph4fc7H](url)

I was trying to convert this image [https://imgur.com/b2OWJDC](url) . 

Though the image is 256x256 pixels, I wanted it to have an output of around 50x50x50.
